### PR TITLE
C15: Change the unit order in Learn to kickoff Unit 2

### PR DESCRIPTION
**Pull request by jmaddox19**
I made a judgement call to move Lightning Talks down a below PSEs and Projects, since students won't need to open them up quite as much, but happy to move it back if anyone thinks consistency in that ordering is important or something

### CODE REVIEW

**Review by tildeee — APPROVED** [review]

**Review by tildeee — APPROVED** [review]
Not sure if this is obvious, but: This file only changes c15/scissors class. To change the others, you'll need to make the same changes to rock and paper (and also to the course.yaml in the root if you want to affect the core preview, too!)

**Comment by jmaddox19** [comment]
Oh, I did not realize that! I assumed we were using one universal course.yml file. Thanks!
I wonder if there's a practical reason not to use one universal file for all classes in the same cohort moving forward...

**Comment by tildeee** [comment]
@jmaddox19 YESSS!!!! I am extremely hopeful that for C16 we use one course.yaml file (or if anything, divide by campus) :D :D :D :D

**Comment by tildeee** [comment]
I guess just to make sure, @CheezItMan , you set up the course.yaml folder structure, did you have a reason for why to not use the same course.yaml for rock, paper, and scissors classes?

**Pull request merged**
